version: '3.8'

services:
  builder:
    image: docker/buildx:latest
    container_name: builder
    command: >
      sh -c "docker buildx create --bootstrap --use &&
             docker buildx inspect --bootstrap"

  arm-build:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: thezyrex/ros2_worm_multiplayer:arm64
    depends_on:
      - builder

  amd64-build:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: thezyrex/ros2_worm_multiplayer:amd64
    depends_on:
      - builder